version: '3.8'

services:
  api:
    build: ./astro/backend
    ports:
      - "3001:3001"
    networks:
      - vnetwork

  web:
    build: ./astro
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - vnetwork

networks:
  vnetwork:
    driver: bridge
