version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapea el puerto 3000 del contenedor al 3000 de la máquina host
    volumes:
      - ./astro:/app # Sincroniza el código del proyecto completo para facilitar el desarrollo
    environment:
      - NODE_ENV=development
